# Generated by Django 6.0.2 on 2026-03-02 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='provider',
            field=models.CharField(choices=[('mk2', 'MK2'), ('ugc', 'UGC'), ('gaumont', 'Gaumont')], default='mk2', max_length=20),
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='core.theater')),
            ],
        ),
    ]
